
tf.init:
	terraform -chdir=iac init
tf.plan:
	terraform -chdir=iac plan
tf.apply:
	terraform -chdir=iac apply -auto-approve
tf.output:
	terraform -chdir=iac output
tf.destroy:
	terraform -chdir=iac destroy