AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda template
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Layers:
      - arn:aws:lambda:us-east-1:546275881527:layer:xray-python3:3
      # - arn:aws:lambda:us-east-1:546275881527:layer:boto3-1-26-101:4
      - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:38
      # - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
    Runtime: python3.11
    MemorySize: !Ref pFnMemory
    Timeout: !Ref pFnTimeout
    Tracing: Active
Parameters:
  pFnMemory:
    Type: Number
  pFnTimeout:
    Type: Number
Resources:
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: xray
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn.handler
      Role: !GetAtt FnRole.Arn
      LoggingConfig:
        ApplicationLogLevel: INFO
        LogFormat: JSON
        SystemLogLevel: INFO
      # AutoPublishAlias: live
      # DeploymentPreference:
      #   Type: Linear10PercentEvery1Minute
      #   Hooks:
      #     PreTraffic: !Ref PreTrafficFn
      # Environment:
      #   Variables:
      #     SECRETS_MANAGER_TIMEOUT_MILLIS: 1000
      #     SECRETS_MANAGER_TTL: 300
      # Layers:
      #   - !Ref LayerTbd
      Tags:
        application:group: templates
        application:subgroup: lambda
        application:owner: heeki
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Fn}'
      RetentionInDays: 7
  # LayerTbd:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     CompatibleRuntimes:
  #       - python3.8
  #       - python3.9
  #       - python3.10
  #       - python3.11
  #     ContentUri: ../tmp/tbd
  #     LayerName: tbd
  #     Description: tbd==0.0.306
Outputs:
  outFn:
    Value: !Ref Fn
  # outLayerTbd:
  #   Value: !Ref LayerTbd
