AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway infrastructure template
Transform: AWS::Serverless-2016-10-31
Parameters:
  pDomainName:
    Type: String
  pHostedZoneId:
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref pDomainName
      DomainValidationOptions:
        - DomainName: !Ref pDomainName
          HostedZoneId: !Ref pHostedZoneId
      ValidationMethod: DNS
  Domain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref pDomainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref Certificate
  DomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref pHostedZoneId
      Name: !Ref pDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt Domain.RegionalHostedZoneId
        DNSName: !GetAtt Domain.RegionalDomainName
Outputs:
  outCertificateArn:
    Value: !Ref Certificate
